#!/usr/bin/env bash
set +x

_ansible_environments() {
  case ${COMP_WORDS[COMP_CWORD-1]} in
    -h | --help)
      COMPREPLY=()
      ;;
    *)
      COMPREPLY=($(compgen -W "-h --help" -- "${COMP_WORDS[COMP_CWORD]}"))
      ;;
  esac
}

complete -F _ansible_environments ansible-environments
